# Generated by Django 4.0.1 on 2022-01-25 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipesApp', '0002_alter_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('user', 'name')},
        ),
    ]
